### ISSUE TITLE
When charging, no charging icon

### ISSUE THREAD

**Issue by yooouuri** [CyanogenMod/android_device_oneplus_oneplus3#25]
Affected: cm-14.1-20161109-NIGHTLY-oneplus3
Gapps: open_gapps-arm64-7.1-nano-20161109

Coming from CB 5.5 and installed modified TWRP by eng.stk

When i plug in the phone, the charging icon wont show up... The phone is charging!

**Comment by infamousrev** [comment]
I have the same problem, the phone charges, but it is like the phone does not know it is charging, this can be annoying for various reasons, since apps will think you phone is not charging while it actually is.

I narrowed the problem down to:
11-14 19:24:23.921  2691  2691 I SystemServiceManager: Starting com.android.server.BatteryService
11-14 19:24:23.939  2691  2851 E BatteryStatsService: no controller energy info supplied

Somehow the BatteryStatsService is not getting the information.

Based on the source of this service:
https://github.com/android/platform_frameworks_base/blob/master/services/core/java/com/android/server/am/BatteryStatsService.java

The file states:
Fetches data from external sources (WiFi controller, bluetooth chipset) and updates
     \* batterystats with that information.

Thats how far I got to far. Somehow it is not getting any battery-stats from the aforementioned source.

**Comment by yooouuri** [comment]
The maintainer is aware of this issue!

**Comment by infamousrev** [comment]
Just to add, Testing this issue further it pointed a lot in the direction of a firmware issue.

So I decided to re-install using oneplus 3 oxygenos OS 3.5.5 as a base. This solved the issue for me.

Originally I installed using the firmware CyanogenMod_14.1_Firmware_Modem-flo071.zip, but that is no longer the newest one.

**Comment by yooouuri** [comment]
@infamousrev i also came from 3.5.5.. So i don't know why it does not work for me..
